version: "3.8"

services:
  ocis:
    image: owncloud/ocis:latest
    container_name: ocis
    restart: always
    ports:
      - "9200:9200"
    environment:
      - OCIS_URL=https://drive.buunk.org
      - OCIS_INSECURE=false
      - PROXY_TLS=false
      - PROXY_HTTP_ADDR=0.0.0.0:9200
      - IDP_INSECURE=false
      - OCIS_OIDC_ISSUER=https://drive.buunk.org
    volumes:
      - /data/nfs/ocis:/var/lib/ocis
